### ISSUE TITLE
If decimal separator is pressed when CurrencyEditText is empty, a zero should be added to left side of decimal separator. 

### ISSUE THREAD

**Issue by yigitserin** [yigitserin/CurrencyEditText#3]
How to reproduce:

Insert a decimal separator and type some 99. It looks like `.99` but it should be `0.99`.

**Comment by kelvisbefore** [comment]
I'd like to take care of this, will prep a PR this week!

**Comment by kelvishardwork** [comment]
I'd like to take care of this, will prep a PR this week.

**Comment by f4ww4z** [comment]
I'd like to work on this issue, preparing PR right now.

**Comment by yigitserin** [comment]
Fixed in #4.
