### ISSUE TITLE
Remove duplicate code in format() function

### ISSUE THREAD

**Issue by f4ww4z** [yigitserin/CurrencyEditText#5]
In the current [format](https://github.com/yigitserin/CurrencyEditText/blob/5837c109f06f1987e03ef0e9a90e06e144514940/currencyedittext/src/main/java/com/yigitserin/currencyedittext/CurrencyEditText.java#L193) function, there are [2 pieces of the same code](https://github.com/yigitserin/CurrencyEditText/blob/5837c109f06f1987e03ef0e9a90e06e144514940/currencyedittext/src/main/java/com/yigitserin/currencyedittext/CurrencyEditText.java#L197-L207) in the if blocks which can be simplified, to increase the overall consistency of the function and make the code more readable.

**Comment by f4ww4z** [comment]
@yigitserin May I work on this issue?

**Comment by yigitserin** [comment]
Fixed in #6.
